
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdEUHghL4P3HfXbgM3ZXLUFbx3gSA0T8
"""

!pip install Wordcloud

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

shop = pd.read_csv('shopping_trends_updated1.csv')

shop.shape

shop.to_excel('shopping_trends_updated.xlsx')

shop.head()

shop.dtypes

shop.columns

shop.info()

shop.shape

shop.isnull().sum()

print(f"The unique values of the 'Gender' column are: {shop['Gender'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Category' column are: {shop['Category'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Size' column are: {shop['Size'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Subscription Status' column are: {shop['Subscription Status'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Shipping Type' column are: {shop['Shipping Type'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Discount Applied' column are: {shop['Discount Applied'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Promo Code Used' column are: {shop['Promo Code Used'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Payment Method' column are: {shop['Payment Method'].unique()}")

shop['Age'].value_counts()

shop['Age'].mean()

shop['Gender'].unique()

shop['Age_category'] = pd.cut(shop['Age'], bins= [0,15, 18 , 30 , 50 , 70] , labels= ['child' , 'teen' , 'Young Adults' ,'Middle-Aged Adults'
                                                                                             , 'old'] )

fig = px.histogram(shop , y ='Age', x ='Age_category')
fig.show()

shop.columns

shop['Category'].unique()

shop.groupby('Category')['Purchase Amount (USD)'].mean()

shop.columns

sns.barplot(shop , x = 'Gender' , y = 'Purchase Amount (USD)')

shop.groupby('Category')['Item Purchased'].value_counts()

fig = px.histogram(shop , x = 'Item Purchased' , color = 'Category')
fig.show()

shop_dup=shop[shop.duplicated()]
shop_dup

shop["Gender"].unique()

shop.describe()

shop.describe(include='object')

### Descriptive analysis

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# %matplotlib inline

shop['Age_category'] = pd.cut(shop['Age'], bins=[0,15,18,30,50,70], labels=['child','teen','Young Adults','Middle-Aged Adults','old'])

shop.head()

plt.hist(shop["Age"],bins=20)

shop["Gender"].value_counts().plot(kind='bar')

data=shop["Gender"].value_counts()
data.plot(kind ='pie',explode = (0,0.1),autopct='%1.1f%%')
plt.xlabel("Gender")

ax = shop['Category'].value_counts().plot(kind='bar',rot=0)
for p in ax.patches:
  ax.annotate(int(p.get_height()), (p.get_x()+0.25, p.get_height()+1),ha='center')

plt.xlabel("Category",weight='bold')
plt.ylabel("Number of occurance",weight='bold')
plt.show()

plt.figure(figsize=(20,6))
data = shop['Category'].value_counts()
explode = [0.1]*len(data)
data.plot(kind='pie',explode=explode,autopct='%1.1f%%')
plt.xlabel("Category")
plt.legend()
plt.show()

data= shop['Season'].value_counts()
data

plt.figure(figsize=(20,6))
data = shop['Season'].value_counts()
explode = [0.1]*len(data)
data.plot(kind='pie',explode=explode,autopct='%1.1f%%')
plt.xlabel("Category")
plt.legend()
plt.show()

shop.columns

shop["Subscription Status"].unique()

sns.barplot(shop , x = 'Subscription Status' , y = 'Purchase Amount (USD)')

shop.groupby('Payment Method')['Purchase Amount (USD)'].mean().sort_values(ascending=False)

sns.barplot(x="Payment Method",y='Purchase Amount (USD)',data=shop)

shop.columns

shop.info()

num_fea = shop[["Age","Purchase Amount (USD)","Review Rating","Previous Purchases"]]
num_fea.head()

cor_mat = num_fea.corr()
cor_mat

plt.figure(figsize=(5,3))
sns.heatmap(cor_mat,annot=True,cmap='coolwarm')